[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
upload_protocol = espota
upload_port = relay.local
build_flags =
  -D APP_VERSION=\"0.1.0\"
