[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -D APP_VERSION=\"0.1.0\"

[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = relay.local
